controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - head_joint
      - left_grip_joint
      - right_grip_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: Start-Arm
  - group: gripper
    pose: Start-Grip