<?xml version="1.0"?>
<robot name="diffbot_2wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!--Masses-->
<xacro:property name="chassis_mass" value="35"/>
<!--xacro:property name="wheel_mass" value="0.0283495"/-->
<xacro:property name="wheel_mass" value="0.1"/>
<xacro:property name="caster_mass" value="13"/>

<!--Dimensions-->
<xacro:property name="chassis_length" value="0.13"/>
<xacro:property name="chassis_width" value="0.1095375"/>
<xacro:property name="chassis_height" value="0.0381"/>
<xacro:property name="caster_radius" value="0.02175"/>
<xacro:property name="wheel_radius" value="0.02175"/>
<xacro:property name="wheel_length" value="0.0254"/>

<!--Positions-->
<xacro:property name="wheel_x_pos" value="${chassis_length / 4}"/>
<xacro:property name="wheel_y_pos" value="${(chassis_width / 2) + (wheel_length / 2)}"/>
<xacro:property name="wheel_z_pos" value="-0.01"/>
<xacro:property name="caster_x_pos" value="${-(chassis_length / 4)}"/>
<xacro:property name="caster_y_pos" value="0"/>
<xacro:property name="caster_z_pos" value="-0.01"/>

<!--Inertial 1-->
<xacro:macro name="chassis_inertial" params="mass">
    <inertial>
        <mass value="${mass}"/>
        <inertia ixx="${(1/12) * chassis_mass * ( (chassis_height * chassis_height) + (chassis_length * chassis_length)) }" ixy="0" ixz="0"
                iyy="${(1/12) * chassis_mass * ( (chassis_width * chassis_width) + (chassis_height * chassis_height)) }" iyz="0" 
                izz="${(1/12) * chassis_mass * ( (chassis_width * chassis_width) + (chassis_length * chassis_length)) }"/>
        </inertial>
</xacro:macro>

<!--Inertial 2-->
<xacro:macro name="wheel_inertial" params="mass"> <!--True inertial measurements for wheels are too small, so they're substituted with 0.1-->
    <inertial>
        <mass value="${mass}"/>
        <inertia ixx="0.1" ixy="0" ixz="0"
                iyy="0.1" iyz="0" 
                izz="0.1"/>
        </inertial>
</xacro:macro>

<!--Inertial 3-->0.1
<xacro:macro name="caster_inertial" params="mass">
    <inertial>
        <mass value="${mass}"/>
        <inertia ixx="${(2/5) * caster_mass * (caster_radius * caster_radius) }" ixy="0" ixz="0"
                iyy="${(2/5) * caster_mass * (caster_radius * caster_radius) }" iyz="0" 
                izz="${(2/5) * caster_mass * (caster_radius * caster_radius) }"/>
        </inertial>
</xacro:macro>

<!--Base Footprint-->  
    <link name="base_footprint"></link>

    <joint name="base_footprint_to_base_link" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius + 0.005}" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
    </joint>

<!--Base Link-->  
    <link name="base_link">   
        
        <pose>0 0 0.1    0 0 0</pose> <!--Where to place robot in Gazebo-->

        <xacro:chassis_inertial mass="${chassis_mass}"/>

        <collision>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange">
                <color rgba="1 0.647 0 1"/>
            </material>
        </visual>
    </link>

    <gazebo reference="base_link">
        <material>Gazebo/Orange</material>
    </gazebo>


<!--Rear Caster-->
    <link name="caster_link">
        
        <xacro:caster_inertial mass="${caster_mass}"/>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="grey">
                <color rgba="0.392 0.392 0.392 1"/>
            </material>
        </visual>
    </link>

    <joint name="caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_link"/>
        <origin xyz="${caster_x_pos} ${caster_y_pos} ${caster_z_pos}" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
    </joint>

    <gazebo reference="caster_link">
        <mu1>0.0</mu1>
        <mu2>0.0</mu2>
        <material>Gazebo/Red</material>
    </gazebo>

    
<!--Right Wheel--> 
    <link name="right_wheel">
        
        <xacro:wheel_inertial mass="${wheel_mass}"/>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="black">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
    </link>

    <joint name="joint_right_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="${wheel_x_pos} -${wheel_y_pos} ${wheel_z_pos}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="10000" velocity="1000"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

<!--Left Wheel--> 
    <link name="left_wheel">
        
        <xacro:wheel_inertial mass="${wheel_mass}"/>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="black">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
    </link>

    <joint name="joint_left_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="${wheel_x_pos} ${wheel_y_pos} ${wheel_z_pos}" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="10000" velocity="1000"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

<!-- Hokuyo Laser --> 
    <link name="hokuyo_link"> 
        <collision> 
            <origin xyz="0 0 0" rpy="0 0 0"/> 
            <geometry> 
                <box size="0.1 0.1 0.1"/> 
            </geometry> 
        </collision> 
        <visual> 
            <origin xyz="0 0 0" rpy="0 0 0"/> 
            <geometry>
                <!--Mesh obtained from  https://github.com/ros-simulation/gazebo_ros_demos--> 
                <mesh filename="package://diffbot_1/meshes/hokuyo.dae"/> 
            </geometry> 
        </visual> 
        <inertial> 
            <mass value="1e-5"/> 
            <origin xyz="0 0 0" rpy="0 0 0"/> 
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" /> 
        </inertial> 
    </link>

    <joint name="hokuyo_joint" type="fixed"> 
        <axis xyz="0 1 0" /> 
        <origin xyz="${chassis_length / 8} 0 ${chassis_height}" rpy="0 0 0"/> 
        <parent link="base_link"/> 
        <child link="hokuyo_link"/> 
    </joint>

<!-- Gazebo Hokuyo --> 
    <gazebo reference="hokuyo_link"> 
        <sensor type="ray" name="head_hokuyo_sensor"> 
            <pose>0 0 0 0 0 0</pose> 
            <visualize>true</visualize> 
            <update_rate>40</update_rate> 
                <ray> 
                    <scan> 
                        <horizontal> 
                            <samples>720</samples>
                            <resolution>1</resolution> 
                            <min_angle>-1.570796</min_angle> 
                            <max_angle>1.570796</max_angle>
                        </horizontal> 
                    </scan> 
                    <range> 
                        <min>0.10</min> 
                        <max>30.0</max> 
                        <resolution>0.01</resolution> 
                    </range> 
                    <noise> 
                        <type>gaussian</type> 
                        <!-- Noise parameters based on published spec for Hokuyo laser achieving 
                        "+-30mm" accuracy at range < 10m. A mean of 0.0m and stddev of 0.01m will 
                        put 99.7% of samples within 0.03m of the true reading. --> 
                        <mean>0.0</mean> 
                        <stddev>0.01</stddev> 
                    </noise> 
                </ray> 
                <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so"> 
                    <topicName>/rrbot/laser/scan</topicName> 
                    <frameName>hokuyo_link</frameName> 
                </plugin> 
        </sensor> 
    </gazebo>

<!--Gazebo Plugin-->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>20</updateRate>
            <leftJoint>joint_left_wheel</leftJoint>
            <rightJoint>joint_right_wheel</rightJoint>
            <wheelSeparation>0.1095375</wheelSeparation>
            <wheelDiameter>0.0635</wheelDiameter>
            <torque>2.5</torque>
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <robotBaseFrame>base_footprint</robotBaseFrame>
        </plugin>
    </gazebo>
</robot>
